### ISSUE TITLE
Git changes compare does not work with the editor

### ISSUE THREAD

**Issue by Skons** [adamerose/vscode-markdown-wysiwyg#16]
When a markdown file is changed, and you want to view the changes through the `Source Control` page, a changed file is opened in a compare window with the editor opened. The editor does not highlight the changes and therefor the changes are hard to see. I think it would be nice if the editor does not show up in the changes but the raw file is shown in that window.

**Comment by adamerose** [comment]
It's because file comparisons just use the default editor. The solution would be to change the default editor for .md back to the Built-In Text Editor. This happens not just with the Source Control page but anything that does a comparison like the `File: Compare Active File With...` command.

IMO the ideal behavior would be that VS Code should use whatever editor you currently have open to show the comparison rather than just the default for the filetype, but this would be an upstream change.
