### ISSUE TITLE
-> and <- automatically creates → symbols

### ISSUE THREAD

**Issue by ssmooncoder** [adamerose/vscode-markdown-wysiwyg#6]
This is the cleanest markdown extension I've used so far, but it seems like the CKEditor you built on top of causes a few problems (e.g. the auto comment stripping and special character escapes)

Try doing `->` in inline code backticks and it'll convert before the closing backtick.

**Comment by adamerose** [comment]
Yeah this behavior is part of CKEditor5, the documentation is [here](https://ckeditor.com/docs/ckeditor5/latest/features/text-transformation.html). Unlike the other issues this one is just a plugin that I can easily remove. I just included it because it was in the list of defaults for the classic CKE5 build, but now that you mention it I do agree it's probably not desired behavior for most users including myself so I'll remove it in my next release.
